# Generated by Django 5.0.6 on 2024-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ModelApi", "0003_blog_feedbackform_video"),
    ]

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.TextField(default="")),
                ("Price", models.IntegerField()),
                ("Mrp", models.TextField(default="")),
                ("Rating", models.TextField(default="")),
                ("Img", models.TextField(default="")),
                ("Description", models.TextField(default="")),
            ],
        ),
    ]
